### ISSUE TITLE
How to use mempooled save ubyte[]?

### ISSUE THREAD

**Issue by zoujiaqing** [tchaloupka/mempooled#1]
Like this sample code:

```D

import std.stdio;

void main()
{
	import mempooled.fixed;

	auto pool = fixedPool!(ubyte, 64);
	ubyte* c = pool.alloc();

	c = cast(ubyte[]) "Hello world";

	writeln(c);
}

```

**Comment by tchaloupka** [comment]
Hi.
With just `ubyte` as a pooled type, it won't work as internally `FixedPool` needs 4B to store linked list inside it.
It works in a way that it can provide fixed sized items from a fixed number of preallocated items.

Your example can look something like this:
```D
@trusted unittest
{
    {
        auto pool = fixedPool!(128, 1024);
        auto str = pool.allocVoid!(char[4]);
        str[0..4] = "foo\0";
        printf("%s\n", str.ptr);
        pool.dealloc(str);
    }

    {
        auto pool = fixedPool!(char[128], 1024);
        auto str = pool.allocVoid();
        str[0..4] = "foo\0";
        printf("%s\n", str.ptr);
        pool.dealloc(str);
    }
}
```

First pool means it has 1024 items (`numBlocks`) each of size 128B (`blockSize`), that can be used with any type that fits into those 128B.
Other one is basically the same but is limited only to that one type of item.

`allocVoid` vs `alloc` differs just in how it initializes the allocated type. With void variant it doesn't use default type initializer (similar with ie. `int foo = void;`).

Hope this helps.

**Comment by zoujiaqing** [comment]
Thank you ;)
